apiVersion: v1
kind: Pod
metadata:
  name:  mysite
  labels:
    function: webserver
spec:
  containers:
  - name: httpd
    image: ghcr.io/noelisabal/cis9216231717:milestone-4.1
    ports:
    - containerPort: 80
  env:
   env: 
    - name: SECRET_KEY
      value: something
    - name: PORT
      value: '80'