apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
  - name: postgres
    image: docker.io/postgres:14.1
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_PASSWORD
      value: "django"
    - name: POSTGRES_DB
      value: "mysite"
